### ISSUE TITLE
Failed to save model as .hdf5

### ISSUE THREAD

**Issue by ProV1denCEX** [Meatssauce/SCINet#2]
Hey, I got an `OSError: Unable to create link (name already exists)`  when I tried to save the model via the ModelCheckPoint callback.

(I've already implemented get_config() method for StackedSciNet class).

It shows that we have some weights' name duplicated like b'total: 0' or b'count: 0' in the StackedSciNet layer. But I can't figure out where they are.

![图片](https://user-images.githubusercontent.com/46249847/143209057-7fd98e07-7385-411a-9558-04a584191d58.png)

Do you know how to solve the problem? Thx!

**Comment by ProV1denCEX** [comment]
Code for reproduce this error:

In SCINet.py:
```
class StackedSciNet:
    def get_config(self):
        """
        Returns the config of a the layer. This is used for saving and loading from a model
        :return: python dictionary with specs to rebuild layer
        """
        config = super(StackedSciNet, self).get_config()
        return config
```

In train_original.py
```
from tensorflow.python.keras.saving.save import save_model

save_model(model, 'test.hdf5')
```

**Comment by Meatssauce** [comment]
Fixed.
